spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: X
            client-secret: X
            redirect-uri: http://localhost:9285/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver


          kakao:
            client-id: kakao rest api key
            redirect-uri: https://i8b103.p.ssafy.io/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: kakao client secret key
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client_name: kakao


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: jwt secret key


KAKAO_CLIENT_ID: kakao rest api key
KAKAO_CLIENT_SECRET: kakao client secret key
